### ISSUE TITLE
[翻訳宣言] trans/faq/native の翻訳

### ISSUE THREAD

**Issue by kkeeth** [ionic-jp/ionic-docs#20]
### 目的 (`x`マークをつけてください)
```
- [x] 翻訳宣言
- [ ] 要望・意見
- [ ] その他
```

### 翻訳するファイル（翻訳宣言の場合）

`src/pages/faq/native.md`

**Comment by rdlabo** [comment]
https://github.com/ionic-jp/ionic-docs/pull/21 でマージしました。ありがとう！！
