### ISSUE TITLE
[翻訳宣言]ion-listコンポーネントの翻訳

### ISSUE THREAD

**Issue by sam8helloworld** [ionic-jp/ionic-docs#28]
## 目的 (`x`マークをつけてください)
```
- [x] 翻訳宣言
- [ ] 要望・意見
- [ ] その他
```
## 翻訳するファイル（翻訳宣言の場合）
`src/translate/api/list.readme.md`

**Comment by sam8helloworld** [comment]
```
Lists are made up of multiple rows of items which can contain text, buttons, toggles,
icons, thumbnails, and much more. Lists generally contain items with similar data content, such as images and text.
```
上記のようにオリジナルの英文では`toggles,`の部分で何故か改行が入っており、
翻訳の際に行を揃えるのが難しい問題が発生してしまいました。

この改行は無視していいやつですかね？

**Comment by rdlabo** [comment]
こちらも適当なところで改行いただきますようお願いしますー！（改行は整形することが目的ではなく、本家が変更した行数を把握するのが目的だからです）

お手数をおかけしますがお願いいたします！
