### ISSUE TITLE
[翻訳宣言]ion-radioコンポーネントの翻訳

### ISSUE THREAD

**Issue by sp-ice** [ionic-jp/ionic-docs#31]
# 目的 (xマークをつけてください)
```
- [x] 翻訳宣言
- [ ] 要望・意見
- [ ] その他
```

# 翻訳するファイル（翻訳宣言の場合）
```
src/translate/api/radio.readme.md
```

# 概要（翻訳宣言以外の場合）

# 備考

**Comment by rdlabo** [comment]
thanks! close by https://github.com/ionic-jp/ionic-docs/commit/5bc62e4342db29f191be7e4a02570d1a4bc743cc
