### ISSUE TITLE
[翻訳宣言]ion-refresherコンポーネントの翻訳

### ISSUE THREAD

**Issue by sp-ice** [ionic-jp/ionic-docs#32]
# 目的 (xマークをつけてください)
```
- [x] 翻訳宣言
- [ ] 要望・意見
- [ ] その他
```

# 翻訳するファイル（翻訳宣言の場合）
```
src/translate/api/refresher.readme.md
```

# 概要（翻訳宣言以外の場合）

# 備考

**Comment by rdlabo** [comment]
thanks. close from https://github.com/ionic-jp/ionic-docs/commit/9a7e5c696b818b679f40c9ec2d04c7670bb60e5b
