### ISSUE TITLE
[翻訳宣言]ion-noteコンポーネントの翻訳

### ISSUE THREAD

**Issue by sam8helloworld** [ionic-jp/ionic-docs#33]
## 目的 (`x`マークをつけてください)
```
- [x] 翻訳宣言
- [ ] 要望・意見
- [ ] その他
```
## 翻訳するファイル（翻訳宣言の場合）
`src/translate/api/note.readme.md`

**Comment by rdlabo** [comment]
@sam0830 
こちらご進捗いかがでしょうか？？もしご多忙などで難しければ、一旦closeにしていただけましたら幸いですー！

**Comment by sam8helloworld** [comment]
@rdlabo 
すいません。翻訳自体は終わってるので、仕事終わりにPR出します。
お待たせしました。

**Comment by rdlabo** [comment]
@sam0830  ありがとうございます。お願いいたしますー！
