### ISSUE TITLE
[翻訳宣言] faq/glossary の翻訳

### ISSUE THREAD

**Issue by kkeeth** [ionic-jp/ionic-docs#41]
### 目的 (`x` マークをつけてください)

```
- [x] 翻訳宣言
- [ ] 要望・意見
- [ ] その他
```

### 翻訳するファイル（翻訳宣言の場合）
`src/pages/faq/glossary.md`

### 備考
対象ページはこちら。

https://ionicframework.jp/docs/faq/glossary

PR #43

**Comment by rdlabo** [comment]
👍

**Comment by kkeeth** [comment]
こっちはまだ翻訳中ですので、reopenしますーw

**Comment by rdlabo** [comment]
あら、すまぬ。了解ですー！

**Comment by rdlabo** [comment]
🎉
