### ISSUE TITLE
[翻訳宣言] angular/your-first-app の翻訳 

### ISSUE THREAD

**Issue by kkeeth** [ionic-jp/ionic-docs#44]
### 目的 (`x` マークをつけてください)

```
- [x] 翻訳宣言
- [ ] 要望・意見
- [ ] その他
```

### 翻訳するファイル（翻訳宣言の場合）
`src/pages/angular/your-first-app.md`

### 備考
対象ページはこちら。

https://ionicframework.jp/docs/angular/your-first-app

**Comment by rdlabo** [comment]
🅰

**Comment by rdlabo** [comment]
GitHubで A の絵文字だすと、暗いのねｗ
