### ISSUE TITLE
master ブランチにてエラー

### ISSUE THREAD

**Issue by kkeeth** [ionic-jp/ionic-docs#58]
**Describe the bug**
master ブランチをプルして npm run start したら、`scripts/build-data/api-reference.ts` にて

```
Cannot find module '../data/translated-api.json' or its corresponding type declarations
```

と言われましたー

**Screenshots**
<img width="1114" alt="スクリーンショット 2020-10-29 0 10 25" src="https://user-images.githubusercontent.com/4125257/97455417-2a858f80-197b-11eb-9ee6-2203c2628f9b.png">

**Comment by rdlabo** [comment]
`npm run translate` してみたらいかがでしょうかー？？

**Comment by kkeeth** [comment]
@rdlabo 
すみません、そのコマンドの実行が漏れていました💦
問題なく動きましたので、クローズしますー。
